### ISSUE TITLE
Highly dangerous to use flawed WD encryption, it seems

### ISSUE THREAD

**Issue by nealmcb** [KenMacD/wdpassport-utils#23]
For emergency use when needing to get data off a disk that is encrypted this way, this might be handy. Thanks.

But based on security expert research and the reporting noted here, I'd stay far away from Western Digital's encryption efforts (or really any closed-source encryption tools):

[Western Digital's hard drive encryption is useless\. Totally useless • The Register](https://www.theregister.co.uk/2015/10/20/western_digital_bad_hard_drive_encryption/)

Linux already has many excellent options for encrypting disks, so I'd suggest using those instead, and making these points in the README.

**Comment by DanLukes** [comment]
Neal McBurnett wrote on 2. 4. 2019 17:24:
> [Western Digital's hard drive encryption is useless\. Totally useless • The Register](https://www.theregister.co.uk/2015/10/20/western_digital_bad_hard_drive_encryption/)

It's old and well known article/fact for (most of) us. I hope it's not 
new even for you.

> Linux already has many excellent options for encrypting disks

Sounds rather than evangelism than serious argument.

Software based encryption can be used for some usage scenarios. Other 
tasks are requiring hardware encryption support.

Despite WD drives are not secure, storage with OS-independend hardware 
encryption/acces control are still necessary. Fortunately, there are 
some good devices available.

1TB WD drive are low cost (about $80) devices. Devices like iStorage 
diskAshur2 or Apricorn Aegis Padlock Fortress have better security, but 
cost is substantially higher (about $300 for 1TB).

Feel free to use Linux (or other systems supporting it - there are many) 
if software based encryption fulfill your needs.

If you need OS-independent security - evaluate attack vectors you wish 
to avoid, think about value of the data secured, consider other factors 
as well and select appropriate solution. Based on criteria, WD drives 
may or may not be enough for you.

Dan
